# Generated by Django 4.1.7 on 2023-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_clip', '0002_uclip_map_delete_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uclip_map',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uclip_map',
            name='Longitude',
            field=models.FloatField(),
        ),
    ]
