# Generated by Django 4.1.7 on 2023-04-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_clip', '0003_alter_uclip_map_latitude_alter_uclip_map_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='uclip_map',
            name='Path',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
