# Generated by Django 4.1.7 on 2023-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_clip', '0004_uclip_map_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uclip_map',
            name='Html',
            field=models.CharField(max_length=250),
        ),
    ]
